In [ ]:
import numpy as np
import pandas as pd
import config as config

input_file="DATA_RAW_DIR/communes-france-2025.csv"

df = pd.read_csv(input_file,
                 sep=',',
                 encoding='utf-8')
df.head()

/tmp/ipykernel_57435/2862964369.py:6: DtypeWarning: Columns (0: code_insee, 1: dep_code, 2: canton_code, 3: epci_code, 4: code_insee_centre_zone_emploi, 5: code_unite_urbaine) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_file,

,numero,code_insee,nom_standard,nom_sans_pronom,nom_a,nom_de,nom_sans_accent,nom_standard_majuscule,typecom,typecom_texte,...,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve
0,0,01001,L'Abergement-Clémenciat,Abergement-Clémenciat,à Abergement-Clémenciat,de l'Abergement-Clémenciat,l-abergement-clemenciat,L'ABERGEMENT-CLÉMENCIAT,COM,commune,...,4.921,46.153,4.926,6,Rural à habitat dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01001-l-abergemen...
1,1,01002,L'Abergement-de-Varey,Abergement-de-Varey,à Abergement-de-Varey,de l'Abergement-de-Varey,l-abergement-de-varey,L'ABERGEMENT-DE-VAREY,COM,commune,...,5.423,46.009,5.428,6,Rural à habitat dispersé,0.0,communes non pôle,"Abergementais, Abergementaises",https://fr.wikipedia.org/wiki/fr:L'Abergement-...,https://villedereve.fr/ville/01002-l-abergemen...
2,2,01004,Ambérieu-en-Bugey,Ambérieu-en-Bugey,à Ambérieu-en-Bugey,d'Ambérieu-en-Bugey,amberieu-en-bugey,AMBÉRIEU-EN-BUGEY,COM,commune,...,5.360,45.961,5.373,2,Centres urbains intermédiaires,3.0,centres structurants d'équipements et de services,"Ambarrois, Ambarroises",https://fr.wikipedia.org/wiki/fr:Ambérieu-en-B...,https://villedereve.fr/ville/01004-amberieu-en...
3,3,01005,Ambérieux-en-Dombes,Ambérieux-en-Dombes,à Ambérieux-en-Dombes,d'Ambérieux-en-Dombes,amberieux-en-dombes,AMBÉRIEUX-EN-DOMBES,COM,commune,...,4.903,45.996,4.912,5,Bourgs ruraux,1.0,centres locaux d'équipements et de services,Ambarrois,https://fr.wikipedia.org/wiki/fr:Ambérieux-en-...,https://villedereve.fr/ville/01005-amberieux-e...
4,4,01006,Ambléon,Ambléon,à Ambléon,d'Ambléon,ambleon,AMBLÉON,COM,commune,...,5.601,45.750,5.594,6,Rural à habitat dispersé,0.0,communes non pôle,Ambléonais,https://fr.wikipedia.org/wiki/fr:Ambléon,https://villedereve.fr/ville/01006-ambleon

In [ ]:
from sqlalchemy import create_engine, text
import pandas as pd

# ================== PARAMÈTRES ==================
HOST = "localhost"
PORT = xxxx
USER = "xxxx"
PASSWORD = "xxxx"
# ===============================================

engine = create_engine(
    f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}"
)

# Test de connexion
try:
    with engine.connect() as conn:
        result = conn.execute(text("SELECT VERSION()"))
        print("Connexion réussie !")
        print("Version MySQL :", result.scalar())

        # Lister les bases existantes
        dbs = conn.execute(text("SHOW DATABASES")).fetchall()
        print("Bases de données :", [db[0] for db in dbs])
except Exception as e:
    print("Erreur de connexion :", e)

Connexion réussie !
Version MySQL : 5.5.68-MariaDB
Bases de données : ['information_schema', 'arclight-igor', 'arclight-princeps', 'arclight-quad', 'incendies', 'mysql', 'performance_schema', 'test']

In [8]:
create_table = """CREATE TABLE IF NOT EXISTS tmp_commune (
    `code_insee`                     VARCHAR(10)     NOT NULL,
    `nom_standard`                   VARCHAR(100)    NOT NULL,
    `nom_sans_pronom`                VARCHAR(100)    NOT NULL,
    `nom_a`                          VARCHAR(100)    NOT NULL,
    `nom_de`                         VARCHAR(100)    NOT NULL,
    `nom_sans_accent`                VARCHAR(100)    NOT NULL,
    `nom_standard_majuscule`         VARCHAR(100)    NOT NULL,
    `typecom`                        VARCHAR(10)     NOT NULL,
    `typecom_texte`                  VARCHAR(50)     NOT NULL,
    `reg_code`                       SMALLINT        NOT NULL,
    `reg_nom`                        VARCHAR(100)    NOT NULL,
    `dep_code`                       VARCHAR(10)     NOT NULL,
    `dep_nom`                        VARCHAR(100)    NOT NULL,
    `canton_code`                    VARCHAR(10)     NULL,
    `canton_nom`                     VARCHAR(100)    NULL,
    `epci_code`                      VARCHAR(20)     NULL,
    `epci_nom`                       VARCHAR(150)    NULL,
    `academie_code`                  SMALLINT        NOT NULL,
    `academie_nom`                   VARCHAR(100)    NOT NULL,
    `code_postal`                    VARCHAR(10)     NULL,
    `codes_postaux`                  VARCHAR(200)    NULL,
    `zone_emploi`                    INT             NULL,
    `code_insee_centre_zone_emploi`  VARCHAR(10)     NULL,
    `code_unite_urbaine`             VARCHAR(10)     NULL,
    `nom_unite_urbaine`              VARCHAR(100)    NULL,
    `taille_unite_urbaine`           SMALLINT        NULL,
    `type_commune_unite_urbaine`     VARCHAR(50)     NULL,
    `statut_commune_unite_urbaine`   VARCHAR(50)     NULL,
    `population`                     INT             NOT NULL,
    `superficie_hectare`             INT             NOT NULL,
    `superficie_km2`                 INT             NOT NULL,
    `densite`                        DECIMAL(10,2)   NULL,
    `altitude_moyenne`               SMALLINT        NOT NULL,
    `altitude_minimale`              SMALLINT        NOT NULL,
    `altitude_maximale`              SMALLINT        NOT NULL,
    `latitude_mairie`                DECIMAL(9,6)    NOT NULL,
    `longitude_mairie`               DECIMAL(9,6)    NOT NULL,
    `latitude_centre`                DECIMAL(9,6)    NULL,
    `longitude_centre`               DECIMAL(9,6)    NULL,
    `grille_densite`                 TINYINT         NOT NULL,
    `grille_densite_texte`           VARCHAR(50)     NOT NULL,
    `niveau_equipements_services`    TINYINT         NULL,
    `niveau_equipements_services_texte` VARCHAR(100) NULL,
    `gentile`                        VARCHAR(100)    NULL,
    `url_wikipedia`                  VARCHAR(255)    NULL,
    `url_villedereve`                VARCHAR(255)    NOT NULL,

    PRIMARY KEY (`code_insee`),
    INDEX idx_dep (`dep_code`),
    INDEX idx_reg (`reg_code`),
    INDEX idx_nom (`nom_standard`),
    INDEX idx_epci (`epci_code`)
) ENGINE = MyISAM DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;"""

with engine.connect() as conn:
    conn.execute(text("USE incendies"))
    conn.execute(text(create_table))
    print("✅ Table 'communes' créée avec succès (MyISAM)")

✅ Table 'communes' créée avec succès (MyISAM)

In [ ]:
total_inserted = 0
try:
    df = df.drop(columns=["numero"])
    df.to_sql(
            'tmp_commune',
            engine,
            schema="incendies",
            if_exists="append",
            index=False,
            chunksize=5000
        )
    rows = len(df)
    total_inserted += rows
    print(f"→ {rows:6,} lignes insérées")

except Exception as e:
    print(f"Erreur insertion : {e}")

print(f"\nFIN ! Total inséré dans tmp_incendie : {total_inserted:,} lignes")

→ 34,935 lignes insérées

FIN ! Total inséré dans tmp_incendie : 34,935 lignes

In [ ]:
# Chargement des deux tables
df_incendies = pd.read_sql("SELECT * FROM tmp_incendie", engine)
df_communes  = pd.read_sql("SELECT * FROM tmp_commune", engine)

# Jointure
df_joint = df_incendies.merge(
    df_communes,
    left_on="Insee",
    right_on="code_insee",
    how="left"
)

print(f"Jointure pandas : {df_joint.shape}")

Jointure pandas : (142784, 70)

In [18]:
df_joint.head()

,Annee,Numero,Departement,Insee,Nom_Commune,Date_Premiere_Alerte,Surface_Parcourue,Surface_Foret,Surface_Maquis_Garrigues,Autres_Surfaces_Naturelles,...,longitude_mairie,latitude_centre,longitude_centre,grille_densite,grille_densite_texte,niveau_equipements_services,niveau_equipements_services_texte,gentile,url_wikipedia,url_villedereve
0,1973,1,05,05169,Sorbiers,1973-07-03 05:45:00,100000,47000.0,48000.0,0.0,...,5.564,44.362,5.573,7.0,Rural à habitat très dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:Sorbiers (Hau...,https://villedereve.fr/ville/05169-sorbiers
1,1973,4,05,05048,L'Épine,1973-08-22 15:20:00,20000,9400.0,9600.0,0.0,...,5.614,44.425,5.611,7.0,Rural à habitat très dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:L'Épine (Haut...,https://villedereve.fr/ville/05048-l-epine
2,1973,2,05,05178,Ventavon,1973-08-22 16:25:00,10000,4700.0,4800.0,0.0,...,5.906,44.386,5.888,7.0,Rural à habitat très dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:Ventavon,https://villedereve.fr/ville/05178-ventavon
3,1973,3,05,05078,Monêtier-Allemont,1973-08-23 14:15:00,5000,2350.0,2400.0,0.0,...,5.944,44.393,5.934,6.0,Rural à habitat dispersé,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:Monêtier-Alle...,https://villedereve.fr/ville/05078-monetier-al...
4,1973,5,05,05127,Rousset,1973-09-15 20:00:00,150000,70500.0,72000.0,0.0,...,6.233,44.484,6.267,5.0,Bourgs ruraux,0.0,communes non pôle,NaN,https://fr.wikipedia.org/wiki/fr:Rousset (Haut...,https://villedereve.fr/ville/05127-rousset